# Generated by Django 3.1 on 2020-08-12 07:30

import DecorFront.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('caption', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('weight', models.IntegerField()),
                ('published', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proprietary', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=15)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('ward_no', models.IntegerField()),
                ('phone1_no', models.CharField(max_length=10, validators=[DecorFront.validator.mobile_no_validation])),
                ('phone2_no', models.CharField(blank=True, max_length=10, null=True, validators=[DecorFront.validator.mobile_no_validation])),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True, null=True)),
                ('facebook_page_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('facebook_page_name', models.CharField(blank=True, max_length=150, null=True)),
                ('instagram_page_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('instagram_page_name', models.CharField(blank=True, max_length=150, null=True)),
                ('twitter_page_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('twitter_page_name', models.CharField(blank=True, max_length=150, null=True)),
                ('linkedin_page_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('linkedin_page_name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FestivalGreeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('greeting_message', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('status', models.BooleanField(default=False)),
                ('pub_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrontHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='OpeningClosingDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=15, unique=True)),
                ('opening_time', models.IntegerField()),
                ('opening_am_pm', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2)),
                ('closing_time', models.IntegerField()),
                ('closing_am_pm', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('menu_title', models.CharField(max_length=70)),
                ('content', models.TextField()),
                ('published', models.BooleanField()),
                ('navbar', models.BooleanField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WelcomeMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
