# Generated by Django 3.1 on 2020-08-13 18:50

import DecorFront.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_no1',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[DecorFront.validator.mobile_no_validation]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_no2',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[DecorFront.validator.mobile_no_validation]),
        ),
    ]
